### ISSUE TITLE
ACCOGLIENZA TEMPORANEA DEI BAMBINI UCRAINI

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/europehelp.info_segnalazioni#79]
<pre><yamldata>
type: hospitality
offerFromWho: CONADI, Consiglio Nazionale Diritti Infanzia e Adolescenza
title: ACCOGLIENZA TEMPORANEA DEI BAMBINI UCRAINI
recipients: ''
description: "In risposta alle numerose richieste pervenute, il CONADI, Consiglio\
  \ Nazionale Diritti Infanzia e Adolescenza, www.CONADI.it sta organizzando accoglienza\
  \ minori Ucraini.\n\nPreliminarmente sottolineiamo che: NON si tratta di adozione,\
  \ \n\nNON si tratta di affido internazionale, \n\nNON c’è possibilità che i bambini\
  \ vengano adottati in futuro. \n\n✔L’ospitalità è “TEMPORANEA”, cioè legata al periodo\
  \ dell’emergenza; può essere prestata da una famiglia o persona singola.\n\nChi\
  \ volesse dare la propria disponibilità all’accoglienza TEMPORANEA può inviare una\
  \ mail (accoglienza@conadi.it) indicando: \n\n1. Nome, cognome, residenza, numero\
  \ di telefono\n\n2. Numero di bambini ospitabili (uno, due, o nucleo familiare)\n\
  \n3. Età del bambino ospitabile\n\n4. Presenza di altri minori o anziani o animali\
  \ in casa\n\n5. Periodo di disponibilità all’accoglienza \n\nUna volta raccolte\
  \ tutte le disponibilità, CONADI provvederà a contattare l’interessato e a fornire\
  \ tutte le informazioni necessarie."
url: http://www.conadi.it/ucraina
address:
  mode: autocomplete
  address: {}
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente https://github.com/emergenzeHack/europehelp.info_segnalazioni/issues/74
